In [13]:
import numpy as np 
a = np.arange(10,60,5).reshape(2,5)
a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

<h1>1.1 Arrays</h1>

In [17]:
import numpy as np 
print(np.array([8,4,6,0,2]))

[8 4 6 0 2]


In [19]:
print('create a 2-D array by passing a list of list into array().')
A = np.array ([ [1,2,3],[4,5,6] ])
print(A)

print('Access elements of the array with brackets ')
print(A[0,1],A[1,2])

print('The elements of a 2-D array are 1-D arrays')
print(A[0])

create a 2-D array by passing a list of list into array().
[[1 2 3]
 [4 5 6]]
Access elements of the array with brackets 
2 6
The elements of a 2-D array are 1-D arrays
[1 2 3]


In [27]:
A = np.array ([ [3,-1,4],[1,5,-9]])
B = np.array ([ [2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])
np.dot(A,B)

array([[ 19,  13, -52,   7],
       [-30,  21, 103,  39]])

<h1> 1.2 Basic Array opreations<h1/>

In [42]:
x= np.array([3,-4,1])
y= np.array([5,2,3])
print(x+10)
print(y*4)
print(x+y)
print(x*y)

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


<h1>Array Attributes</h1>

In [41]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)
print(A.shape)
print(A.size)

2
(2, 3)
6


<h1> 1.5.1 Array Slicing</h1>

In [16]:
import numpy as np 
x = np.arange(10)
print(x[3])
print(x[:4])
print(x[4:])
print(x[4:8])

3
[0 1 2 3]
[4 5 6 7 8 9]
[4 5 6 7]


In [20]:
y = np.array([10,12,14,16,18])
print(y)
mask = y > 15
print(mask)
print(y[mask])

y[mask] =100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


<h1> 2. Working on iris.csv file</h1>

In [24]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

D:\Programs\anaconda\lib\site-packages\sklearn\datasets\data\iris.csv


In [28]:
import numpy as np 
iris_data = np.genfromtxt(r'D:\Programs\anaconda\lib\site-packages\sklearn\datasets\data\iris.csv',
                          delimiter=",",skip_header=1)
print(iris_data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1